 
<!DOCTYPE html>
<html lang="pt-br">
<head>
<title> Lista </title>
</head>
<body> 
<?php 
$a2 = "nginx                             Official build of Nginx.                        12537               ";                
$a3 = "jwilder/nginx-proxy               Automated Nginx reverse proxy for docker con…   1724                                    ";
$a4 = "richarvey/nginx-php-fpm           Container running Nginx + PHP-FPM capable of…   753                                     ";
$a6 = "bitnami/nginx                     Bitnami nginx Docker Image                      75                                      ";
$a7 = "tiangolo/nginx-rtmp               Docker image with Nginx using the nginx-rtmp…   61                                      ";
$a9 = "nginxdemos/hello                  NGINX webserver that serves a simple page co…   36                                      ";
$a11 = "jlesage/nginx-proxy-manager       Docker container for Nginx Proxy Manager        33                                      ";
$a13 = "privatebin/nginx-fpm-alpine       PrivateBin running on an Nginx, php-fpm & Al…   20                                      ";
$a14 = "schmunk42/nginx-redirect          A very simple container to redirect HTTP tra…   18                                      ";
$a15 = "blacklabelops/nginx               Dockerized Nginx Reverse Proxy Server.          12                                      ";
$a19 = "raulr/nginx-wordpress             Nginx front-end for the official wordpress:f…   12                                      ";
$a21 = "sophos/nginx-vts-exporter         Simple server that scrapes Nginx vts stats a…   6                                       ";
$a22 = "mailu/nginx                       Mailu nginx frontend                            5                                       ";
$a23 = "pebbletech/nginx-proxy            nginx-proxy sets up a container running ngin…   2                                       ";
$a24 = "ansibleplaybookbundle/nginx-apb   An APB to deploy NGINX                          1                                       ";
$a26 = "wodby/nginx                       Generic nginx                                   0                                       ";

echo "<table border=1>"; 
echo "<tr>";
 echo "<td>";
echo($a1);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a2);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a3);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a4);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a5);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a6);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a7);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a8);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a9);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a10);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a11);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a12);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a13);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a14);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a15);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a16);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a17);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a18);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a19);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a20);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a21);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a22);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a23);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a24);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a25);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a26);
echo "</td>";
echo "</tr>";
echo "</table>";
?>
 </body>
 </html>

