 
<!DOCTYPE html>
<html lang="pt-br">
<head>
<title> Lista </title>
</head>
<body> 
<?php 
$a2 = "centos                             The official build of CentOS.                   5885                ";                
$a3 = "ansible/centos7-ansible            Ansible on Centos7                              128                                     ";
$a4 = "jdeathe/centos-ssh                 OpenSSH / Supervisor / EPEL/IUS/SCL Repos - …   114                                     ";
$a5 = "consol/centos-xfce-vnc             Centos container with headless VNC session…   111                                     ";
$a7 = "imagine10255/centos6-lnmp-php56    centos6-lnmp-php56                              58                                      ";
$a10 = "kinogmt/centos-ssh                 CentOS with SSH                                 29                                      ";
$a13 = "nathonfowlie/centos-jre            Latest CentOS image with the JRE pre-install…   8                                       ";
$a14 = "centos/tools                       Docker image that has systems administration…   6                                       ";
$a15 = "drecom/centos-ruby                 centos ruby                                     6                                       ";
$a18 = "darksheer/centos                   Base Centos Image -- Updated hourly             3                                       ";
$a19 = "mamohr/centos-java                 Oracle Java 8 Docker image based on Centos 7    3                                       ";
$a21 = "mcnaughton/centos-base             centos base image                               1                                       ";
$a22 = "indigo/centos-maven                Vanilla CentOS 7 with Oracle Java Developmen…   1                                       ";
$a23 = "blacklabelops/centos               CentOS Base Image! Built and Updates Daily!     1                                       ";
$a26 = "smartentry/centos                  centos with smartentry                          0                                       ";

echo "<table border=1>"; 
echo "<tr>";
 echo "<td>";
echo($a1);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a2);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a3);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a4);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a5);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a6);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a7);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a8);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a9);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a10);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a11);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a12);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a13);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a14);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a15);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a16);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a17);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a18);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a19);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a20);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a21);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a22);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a23);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a24);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a25);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a26);
echo "</td>";
echo "</tr>";
echo "</table>";
?>
 </body>
 </html>

