 
<!DOCTYPE html>
<html lang="pt-br">
<head>
<title> Lista </title>
</head>
<body> 
<?php 
$a3 = "mattrayner/lamp               A simple LAMP docker image running the pre...   145                  ";
$a5 = "greyltc/lamp                  a super secure, up-to-date and lightweight...   97                   ";
$a6 = "fauria/lamp                   Modern, developer friendly LAMP stack. Inc...   73                   ";
$a7 = "lioshi/lamp                   Docker image for LAMP + MySql under debian      13                   ";
$a8 = "dgraziotin/lamp                                                               11                   ";
$a9 = "linuxconfig/lamp              Automated build LAMP stack environment for...   5                    ";
$a10 = "zopnow/lamp-stack             Latest Ubuntu LTS with PHP, MySQL, Apache ...   4                    ";
$a11 = "greyltc/lamp-sshd-aur         LAMP and ssh servers with aur access            4                    ";
$a12 = "shelleyma/lampp2              lampp from github                               3                    ";
$a16 = "lead4good/lamp-php            LAMP Stack PHP                                  2                    ";
$a18 = "drunomics/lamp-redis-solr                                                     1                    ";
$a19 = "thinkiq/lamp                  ThinkIQ Lamp image                              1                    ";
$a21 = "lead4good/lamp-mysql          LAMP-Stack MySQL                                1                    ";
$a24 = "kahatie/lamp                  simple server lamp (linux apache2 mysql ph...   0                    ";
$a25 = "greyltc/lamp-aur              LAMP stack (in Arch with php7) with AUR ac...   0                    ";
$a29 = "mattrayner/lamp               A simple LAMP docker image running the pre...   145                  ";
$a31 = "greyltc/lamp                  a super secure, up-to-date and lightweight...   97                   ";
$a32 = "fauria/lamp                   Modern, developer friendly LAMP stack. Inc...   73                   ";
$a33 = "lioshi/lamp                   Docker image for LAMP + MySql under debian      13                   ";
$a34 = "dgraziotin/lamp                                                               11                   ";
$a35 = "linuxconfig/lamp              Automated build LAMP stack environment for...   5                    ";
$a36 = "zopnow/lamp-stack             Latest Ubuntu LTS with PHP, MySQL, Apache ...   4                    ";
$a37 = "greyltc/lamp-sshd-aur         LAMP and ssh servers with aur access            4                    ";
$a38 = "shelleyma/lampp2              lampp from github                               3                    ";
$a42 = "lead4good/lamp-php            LAMP Stack PHP                                  2                    ";
$a44 = "drunomics/lamp-redis-solr                                                     1                    ";
$a45 = "thinkiq/lamp                  ThinkIQ Lamp image                              1                    ";
$a47 = "lead4good/lamp-mysql          LAMP-Stack MySQL                                1                    ";
$a50 = "kahatie/lamp                  simple server lamp (linux apache2 mysql ph...   0                    ";
$a51 = "greyltc/lamp-aur              LAMP stack (in Arch with php7) with AUR ac...   0                    ";
$a53 = "lead4good/lamp-mysql          LAMP-Stack MySQL                                1                    ";
$a55 = "greyltc/lamp-aur              LAMP stack (in Arch with php7) with AUR ac...   0                    ";
$a58 = "kahatie/lamp                  simple server lamp (linux apache2 mysql ph...   0                    ";
$a61 = "mattrayner/lamp               A simple LAMP docker image running the pre...   145                  ";
$a63 = "greyltc/lamp                  a super secure, up-to-date and lightweight...   97                   ";
$a64 = "fauria/lamp                   Modern, developer friendly LAMP stack. Inc...   73                   ";
$a65 = "lioshi/lamp                   Docker image for LAMP + MySql under debian      13                   ";
$a66 = "dgraziotin/lamp                                                               11                   ";
$a67 = "linuxconfig/lamp              Automated build LAMP stack environment for...   5                    ";
$a68 = "zopnow/lamp-stack             Latest Ubuntu LTS with PHP, MySQL, Apache ...   4                    ";
$a69 = "greyltc/lamp-sshd-aur         LAMP and ssh servers with aur access            4                    ";
$a70 = "shelleyma/lampp2              lampp from github                               3                    ";
$a74 = "lead4good/lamp-php            LAMP Stack PHP                                  2                    ";
$a76 = "drunomics/lamp-redis-solr                                                     1                    ";
$a77 = "thinkiq/lamp                  ThinkIQ Lamp image                              1                    ";
$a79 = "lead4good/lamp-mysql          LAMP-Stack MySQL                                1                    ";
$a81 = "greyltc/lamp-aur              LAMP stack (in Arch with php7) with AUR ac...   0                    ";
$a84 = "kahatie/lamp                  simple server lamp (linux apache2 mysql ph...   0                    ";

echo "<table border=1>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a0);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a1);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a2);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a3);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a4);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a5);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a6);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a7);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a8);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a9);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a10);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a11);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a12);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a13);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a14);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a15);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a16);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a17);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a18);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a19);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a20);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a21);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a22);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a23);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a24);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a25);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a26);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a27);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a28);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a29);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a30);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a31);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a32);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a33);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a34);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a35);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a36);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a37);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a38);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a39);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a40);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a41);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a42);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a43);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a44);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a45);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a46);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a47);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a48);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a49);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a50);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a51);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a52);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a53);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a54);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a55);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a56);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a57);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a58);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a59);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a60);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a61);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a62);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a63);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a64);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a65);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a66);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a67);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a68);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a69);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a70);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a71);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a72);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a73);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a74);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a75);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a76);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a77);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a78);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a79);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a80);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a81);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a82);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a83);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a84);
echo "</td>"; 
echo "</tr>"; 
echo "<tr>"; 
 echo "<td>"; 
echo($a85);
echo "</td>"; 
echo "</tr>"; 
"</table>";
?>
 </body>
 </html>

