 
<!DOCTYPE html>
<html lang="pt-br">
<head>
<title> Lista </title>
</head>
<body> 
<?php 
$a2 = "ubuntu                                                    Ubuntu is a Debian-based Linux operating sys…   10757               ";                
$a3 = "dorowu/ubuntu-desktop-lxde-vnc                            Docker image to provide HTML5 VNC interface …   415                                     ";
$a4 = "rastasheep/ubuntu-sshd                                    Dockerized SSH service, built on top of offi…   245                                     ";
$a5 = "consol/ubuntu-xfce-vnc                                    Ubuntu container with headless VNC session…   214                                     ";
$a6 = "ubuntu-upstart                                            Upstart is an event-based replacement for th…   107                 ";                
$a7 = "neurodebian                                               NeuroDebian provides neuroscience research s…   68                  ";                
$a8 = "1and1internet/ubuntu-16-nginx-php-phpmyadmin-mysql-5      ubuntu-16-nginx-php-phpmyadmin-mysql-5          50                                      ";
$a9 = "ubuntu-debootstrap                                        debootstrap --variant=minbase --components=m…   44                  ";                
$a10 = "nuagebec/ubuntu                                           Simple always updated Ubuntu docker images w…   24                                      ";
$a12 = "1and1internet/ubuntu-16-apache-php-5.6                    ubuntu-16-apache-php-5.6                        14                                      ";
$a13 = "1and1internet/ubuntu-16-apache-php-7.0                    ubuntu-16-apache-php-7.0                        13                                      ";
$a15 = "1and1internet/ubuntu-16-nginx-php-phpmyadmin-mariadb-10   ubuntu-16-nginx-php-phpmyadmin-mariadb-10       11                                      ";
$a16 = "1and1internet/ubuntu-16-nginx-php-5.6                     ubuntu-16-nginx-php-5.6                         8                                       ";
$a17 = "1and1internet/ubuntu-16-nginx-php-5.6-wordpress-4         ubuntu-16-nginx-php-5.6-wordpress-4             7                                       ";
$a18 = "1and1internet/ubuntu-16-apache-php-7.1                    ubuntu-16-apache-php-7.1                        6                                       ";
$a19 = "darksheer/ubuntu                                          Base Ubuntu Image -- Updated hourly             5                                       ";
$a21 = "1and1internet/ubuntu-16-nginx-php-7.0                     ubuntu-16-nginx-php-7.0                         4                                       ";
$a23 = "smartentry/ubuntu                                         ubuntu with smartentry                          1                                       ";
$a24 = "1and1internet/ubuntu-16-sshd                              ubuntu-16-sshd                                  1                                       ";
$a25 = "1and1internet/ubuntu-16-php-7.1                           ubuntu-16-php-7.1                               1                                       ";

echo "<table border=1>"; 
echo "<tr>";
 echo "<td>";
echo($a1);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a2);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a3);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a4);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a5);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a6);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a7);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a8);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a9);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a10);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a11);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a12);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a13);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a14);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a15);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a16);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a17);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a18);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a19);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a20);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a21);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a22);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a23);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a24);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a25);
echo "</td>";
echo "</tr>";
echo "<tr>";
 echo "<td>";
echo($a26);
echo "</td>";
echo "</tr>";
echo "</table>";
?>
 </body>
 </html>

